In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import os

In [2]:
# Folder location string
path = r'C:\Users\nurgul\Linkedin'

In [3]:
# Importing cleaned dataset
df_ind = pd.read_csv('company_industries.csv', index_col=False)

In [4]:
df_ind.head(19)

    company_id                               industry
0     81149246                       Higher Education
1     10033339      Information Technology & Services
2      6049228                             Accounting
3      2641066  Electrical & Electronic Manufacturing
4     96649998                Marketing & Advertising
5     82684341                 Hospital & Health Care
6     82296828      Information Technology & Services
7     86746333               Logistics & Supply Chain
8       718651                       Medical Practice
9      4781041                     Mental Health Care
10     7573454      Information Technology & Services
11     1434753                Architecture & Planning
12       90844     Recreational Facilities & Services
13    91459053                               Internet
14      145145                  Staffing & Recruiting
15     2899710                               Research
16    20338460                      Civil Engineering
17    90633414                  Management Consulting
18     2902815                  Management Consulting

In [5]:
df_ind.shape

(12601, 2)

In [6]:
#Finding Missing Values
df_ind.isnull().sum()

company_id    0
industry      0
dtype: int64

In [7]:
#Finding duplicates 
duplicate_rows = df_ind[df_ind.duplicated()]

# Display the duplicate rows
print("Duplicate Rows except first occurrence:")
print(duplicate_rows)

Duplicate Rows except first occurrence:
Empty DataFrame
Columns: [company_id, industry]
Index: []

In [8]:
# Importing cleaned dataset
df = pd.read_csv('jobs_posts_clean_latest1.csv', index_col=False)

In [9]:
# Merging data frames 
merged_df = pd.merge(df, df_ind, on='company_id', how='inner')

In [10]:
merged_df.head()

,job_id,company_id,title,max_salary,min_salary,work_type,location,applies,views,experience_level,...,approx_salary,name,company_size,state,country,zip_code,skill_abr,salary_category,applies_category,industry
0,3757937095,437225,Principal Cloud Security Architect (Remote),275834.0,205956.0,Full-time,United States,31.256076,96.929148,Mid-Senior level,...,240895.0,"iHerb, LLC",5.0,California,US,92618,IT,high,high,Retail
1,3757935381,19181907,Insights Analyst - Auto Industry,64000.0,58000.0,Full-time,United States,17.361502,130.000000,Entry level,...,61000.0,Escalent,4.0,MI,US,48152,RSCH,medium,medium,Market Research
2,3757935381,19181907,Insights Analyst - Auto Industry,64000.0,58000.0,Full-time,United States,24.096085,130.000000,Entry level,...,61000.0,Escalent,4.0,MI,US,48152,ANLS,medium,high,Market Research
3,3757935381,19181907,Insights Analyst - Auto Industry,64000.0,58000.0,Full-time,United States,31.256076,130.000000,Entry level,...,61000.0,Escalent,4.0,MI,US,48152,IT,medium,high,Market Research
4,3757935001,73013724,Sales Manager,350000.0,125000.0,Full-time,"Coeur d'Alene, ID",18.329151,66.426309,Mid-Senior level,...,237500.0,J. Galt,3.0,Indiana,US,46268,SALE,high,medium,Financial Services

In [11]:
#Finding Missing Values
merged_df.isnull().sum()

job_id               0
company_id           0
title                0
max_salary           0
min_salary           0
work_type            0
location             0
applies              0
views                0
experience_level     0
listed_time          0
approx_salary        0
name                 0
company_size         0
state                0
country              0
zip_code            21
skill_abr            0
salary_category      3
applies_category     0
industry             0
dtype: int64

In [12]:
merged_df.shape

(21056, 21)

In [13]:
merged_df['industry'].unique()

array(['Retail', 'Market Research', 'Financial Services',
       'Motor Vehicle Manufacturing', 'Staffing and Recruiting',
       'Retail Office Equipment', 'Food and Beverage Manufacturing',
       'Wholesale', 'Staffing & Recruiting', 'Hospitals and Health Care',
       'Travel Arrangements', 'Biotechnology Research',
       'Hospital & Health Care', 'Entertainment',
       'Entertainment Providers', 'Food Production',
       'IT Services and IT Consulting',
       'Professional Training & Coaching',
       'Professional Training and Coaching', 'Telecommunications',
       'Truck Transportation', 'Defense and Space Manufacturing',
       'Law Practice', 'Manufacturing', 'Building Materials',
       'Wholesale Building Materials', 'Computer Hardware Manufacturing',
       'Furniture and Home Furnishings Manufacturing',
       'Software Development', 'Retail Apparel and Fashion',
       'Construction', 'Machinery Manufacturing', 'Apparel & Fashion',
       'Hospitality', 'Real Estate', 'Non-profit Organizations',
       'Banking', 'Insurance', 'Mining',
       'Education Administration Programs', 'Spectator Sports',
       'Pharmaceutical Manufacturing', 'Government Administration',
       'Chemicals', 'Chemical Manufacturing',
       'Information Technology & Services', 'Mental Health Care',
       'Restaurants', 'Research Services', 'Automotive',
       'Management Consulting', 'Business Consulting and Services',
       'Civil Engineering', 'Textile Manufacturing',
       'Automation Machinery Manufacturing', 'Accounting',
       'Legal Services', 'Non-profit Organization Management',
       'Wellness and Fitness Services', 'Computer Software',
       'Higher Education', 'Medical Device',
       'Medical Equipment Manufacturing',
       'Outsourcing and Offshoring Consulting',
       'Human Resources Services',
       'Renewable Energy Semiconductor Manufacturing', 'Retail Groceries',
       'Utilities', 'Performing Arts', 'Environmental Services',
       'Gambling Facilities and Casinos', 'Security and Investigations',
       'Individual and Family Services', 'E-Learning Providers',
       'Personal Care Product Manufacturing', 'Newspaper Publishing',
       'Facilities Services', 'Information Services',
       'Advertising Services', 'Biotechnology', 'Pharmaceuticals',
       'Semiconductor Manufacturing',
       'International Trade and Development',
       'Industrial Machinery Manufacturing',
       'Venture Capital and Private Equity Principals',
       'Government Relations Services', 'Computer and Network Security',
       'Computer Games', 'Investment Banking',
       'Primary and Secondary Education', 'Food and Beverage Services',
       'Packaging & Containers', 'Packaging and Containers Manufacturing',
       'Security & Investigations', 'Food & Beverages',
       'Marketing & Advertising', 'Machinery',
       'Architecture and Planning', 'Consumer Services',
       'Education Management', 'Technology, Information and Internet',
       'Human Resources', 'Gambling & Casinos',
       'Health, Wellness & Fitness',
       'Electrical & Electronic Manufacturing',
       'Appliances, Electrical, and Electronics Manufacturing',
       'Computers and Electronics Manufacturing', 'Farming',
       'Beverage Manufacturing',
       'Aviation and Aerospace Component Manufacturing', 'Public Safety',
       'Internet', 'Airlines and Aviation', 'Research',
       'Museums, Historical Sites, and Zoos', 'Paper & Forest Products',
       'Paper and Forest Product Manufacturing',
       'Glass, Ceramics & Concrete',
       'Glass, Ceramics and Concrete Manufacturing', 'Broadcast Media',
       'Broadcast Media Production and Distribution', 'Medical Practices',
       'Outsourcing/Offshoring', 'Luxury Goods & Jewelry',
       'Retail Luxury Goods and Jewelry',
       'Public Relations and Communications Services',
       'Online Audio and Video Media', 'Civic and Social Organizations',
       'Renewables & Environment', 'Defense & Space', 'Semiconductors',
       'Events Services', 'Musicians', 'Consumer Goods', 'Furniture',
       'Transportation/Trucking/Railroad', 'Aviation & Aerospace',
       'International Affairs', 'Wine & Spirits',
       'Religious Institutions', 'Fundraising', 'Armed Forces',
       'Administration of Justice', 'Law Enforcement',
       'Airlines/Aviation',
       'Transportation, Logistics, Supply Chain and Storage',
       'Dairy Product Manufacturing', 'Design Services',
       'International Trade & Development',
       'Mechanical Or Industrial Engineering',
       'Book and Periodical Publishing', 'Design', 'Judiciary',
       'Individual & Family Services', 'Railroad Manufacture',
       'Railroad Equipment Manufacturing', 'Public Policy Offices',
       'Cosmetics', 'Public Relations & Communications',
       'Artists and Writers', 'Executive Offices', 'Photography',
       'Industrial Automation', 'Oil and Gas', 'Media Production',
       'Oil & Energy', 'Publishing', 'Civic & Social Organization',
       'Mining & Metals', 'Wireless', 'Plastics',
       'Museums & Institutions', 'Leisure, Travel & Tourism',
       'Business Supplies & Equipment', 'Translation & Localization',
       'Architecture & Planning', 'Veterinary Services', 'Public Policy',
       'Online Media', 'Package/Freight Delivery',
       'Computer & Network Security', 'Consumer Electronics',
       'Executive Office', 'Sports', 'E-learning',
       'Primary/Secondary Education', 'Music', 'Computer Hardware',
       'Think Tanks', 'Logistics & Supply Chain', 'Writing & Editing'],
      dtype=object)

In [14]:
merged_df.shape

(21056, 21)